sonar.projectKey=trilliumlab_forest-park-reports-server
sonar.organization=trilliumlab
sonar.projectName=forest-park-reports-server
sonar.javascript.lcov.reportPaths=./coverage.lcov
sonar.exclusions=deno-cache/**, drizzle/**, relations/**, reversed/**, test_data/**, ways/**
sonar.python.version=3.10
