sonar.projectKey=trilliumlab_forest-park-reports-server
sonar.organization=trilliumlab
sonar.projectName=forest-park-reports-server
sonar.javascript.lcov.reportPaths=./server/coverage.lcov
sonar.exclusions=deno-cache/**, server/node_modules/**, server/drizzle/**, data/**, input/**, server/test_data/**, editor/**
sonar.python.version=3.10
sonar.sources=server/src
sonar.tests=server/test
