name: Deno Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: ./deno-cache
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - uses: actions/cache@v3
        name: Cache Deno packages
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-cache-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-cache-
      - run: deno lint
